name: CI

on:
  workflow_call

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout the current repo
        uses: actions/checkout@v2
      - name: checkout the private repo
        uses: actions/checkout@v2
        with:
          repository: gopidevvops/githubactions
          path: hubactions
          ref: v3.0
        
      - name: Run a multi-line script
        run: |
          ls -ltr
          
